config:
  PROVIDER_URI: http://34.70.221.143:8545/
  PUB_SUB_TOPIC_PREFIX: projects/staging-btc-etl/topics/crypto_ethereum
  ROOT_ENTITY_TYPE: block
  ENTITY_TYPES: transaction,token_transfer
  GCS_PREFIX: gs://blockchain-etl-streaming/ethereum-etl/streaming-block
