stream:
  image:
    repository: us.gcr.io/staging-btc-etl/merklescience/ethereum-etl
    tag: 1.1.0-streaming
config:
  PROVIDER_URI: http://35.184.209.110:8545/
  ENTITY_TYPES: transaction,token_transfer
  LAG_BLOCKS: 0
  MAX_WORKERS: 10
  BLOCK_BATCH_SIZE: 1
  BATCH_SIZE: 10
  PERIOD_SECONDS: 0
