config:
  LAG_BLOCKS: 0
  CHAIN: bitcoin_cash_sv
  PROVIDER_URI: http://rpcbitc:uen23JHdei89KL90BSIMsei23Tfssd8+we432@34.68.22.183:8332
  GCS_PREFIX: gs://blockchain-etl-streaming/bitcoin_cash_sv-etl/streaming-0-lag
  PUB_SUB_TOPIC_PREFIX: projects/staging-btc-etl/topics/crypto_bitcoin_cash_sv_0_lag
  BLOCK_BATCH_SIZE: 5
  BATCH_SIZE: 5
  PERIOD_SECONDS: 10
  MAX_WORKERS: 10
  RETRY_ERRORS: "False"

stream:
  image:
    repository: us.gcr.io/staging-btc-etl/merklescience/bitcoin-etl
    tag: 1.3.8-streaming
    pullPolicy: Always
  resources:
    requests:
      memory: "2048Mi"
      cpu: "1500m"
    limits:
      memory: "4084Mi"
      cpu: "2500m"