config:
  LAG_BLOCKS: 0
  CHAIN: bitcoin
  PROVIDER_URI: http://rpcbitc:uen23JHdei89KL90BSIMsei23Tfssd8+we432@35.184.92.51:8332
  GCS_PREFIX: gs://blockchain-etl-streaming/bitcoin-etl/streaming_0_lag
  PUB_SUB_TOPIC_PREFIX: projects/staging-btc-etl/topics/crypto_bitcoin_0_lag
  BLOCK_BATCH_SIZE: 1
  BATCH_SIZE: 10
  PERIOD_SECONDS: 1
  MAX_WORKERS: 10

stream:
  resources:
    requests:
      memory: "2048Mi"
    limits:
      memory: "512Mi"
