config:
  LAG_BLOCKS: 6
  CHAIN: bitcoin_cash
  PROVIDER_URI: http://rpcbitc:uen23JHdei89KL90BSIMsei23Tfssd8+we432@34.68.196.145:8332
  GCS_PREFIX: gs://blockchain-etl-streaming/bitcoin_cash-etl/streaming-cointaint
  PUB_SUB_TOPIC_PREFIX: projects/staging-btc-etl/topics/crypto_bitcoin_cash_cointaint
  MAX_WORKERS: "10"